#Frontend deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dev
spec:
  selector:
    matchLabels:
      app: frontend-dev
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-dev
    spec:
      containers:
        - name: frontend-astro
          image: astro-app
          imagePullPolicy: Never
          ports:
            - containerPort: 4321
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-dev
spec:
  selector:
    app: frontend-dev
  ports:
  - port: 4321
    targetPort: 4321

# -------------------

#Backend deployment
---
#postgresql
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres_blog
spec:
  selector:
    matchLabels:
      app: postgres_blog
  template:
    metadata:
      labels:
        app: postgres_blog
    spec:
      containers:
      - name: postgres-blog
        image: postgres-blog
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432

# ENV POSTGRES_HOST=
# ENV POSTGRES_PORT=
# ENV POSTGRES_USER=
# ENV POSTGRES_PASSWORD=
# ENV POSTGRES_NAME=
# ENV POSTGRES_SSLMODE=